Proceso de lectura de archivos CSV

In [1]:
import pandas as pd
import requests

In [7]:
df=pd.read_csv("Titanic.csv")
print(f'total lineas importadas:  {len(df)}')

total lineas importadas:  1309

In [2]:
def leer_datos_csv():
        source="Titanic.csv"
        df=pd.read_csv(source)
        print(f'total lineas importadas:  {len(df)}')
        return df

In [3]:
leer_datos_csv()

total lineas importadas:  1309

,Passengerid,Age,Fare,Sex,sibsp,zero,zero.1,zero.2,zero.3,zero.4,...,zero.12,zero.13,zero.14,Pclass,zero.15,zero.16,Embarked,zero.17,zero.18,2urvived
0,1,22.0,7.2500,0,1,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1,2,38.0,71.2833,1,1,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,1
2,3,26.0,7.9250,1,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,1
3,4,35.0,53.1000,1,1,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,1
4,5,35.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,1305,28.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1305,1306,39.0,108.9000,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,0
1306,1307,38.5,7.2500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1307,1308,28.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1308,1309,28.0,22.3583,0,1,0,0,0,0,0,...,0,0,0,3,0,0,0.0,0,0,0

In [2]:
subject='cooking'
url = f"https://openlibrary.org/subjects/{subject}.json?limit=50"
response = requests.get(url)
data = response.json()
df = pd.json_normalize(data['works'])
df = df[['title', 'key', 'first_publish_year']]
print(f"Batch pulled {len(df)} book records.")

Batch pulled 50 book records.

In [3]:
df.head(10)

,title,key,first_publish_year
0,Kokuritsu Kokkai Toshokan shozō Meijiki kankō ...,/works/OL33207850W,1991
1,Frugal housewife,/works/OL107969W,1829
2,Boston Cooking-School cook book,/works/OL1798750W,1896
3,Como agua para chocolate,/works/OL953162W,1989
4,The Virginia house-wife,/works/OL2653703W,1824
5,On Cooking,/works/OL1874827W,1994
6,Old Cookery Books and Ancient Cuisine,/works/OL1086812W,1886
7,Joy of Cooking,/works/OL267968W,1931
8,The Bartender's Guide,/works/OL7418388W,1862
9,国立 国会 図書館 所蔵 明治期 刋行 図書 マイクロ版 集成,/works/OL39080200W,1991